# This workflow will build a Java project with Maven when a tag is pushed
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
---
name: Java CI with Maven
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11.0.7
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file: :  
        distribution: 'zulu'
    - name: 'Create settings.xml'
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        servers: '[{"id": "github", "username": "${{ github.actor }}", "password": "${{ github.token}}"}, {"id": "github-annotation", "username": "${{ github.actor }}", "password": "${{ github.token }}"}]'
        repositories: '[{"id" : "github", "url" : "https://maven.pkg.github.com/Ubique-OSS/springboot-swagger3"}, {"id" : "github-annotation", "url" : "https://maven.pkg.github.com/Ubique-OSS/springboot-swagger3-annotations"}]'
    - name: Build with Maven
      run: |
        mvn install --file dpppt-config-backend/pom.xml; 
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TESTCONTAINERS_RYUK_DISABLED: true
    - name: shasum
      run: shasum -a 256 dpppt-config-backend/target/dpppt-config-backend.jar > dpppt-config-backend/target/dpppt-config-backend.jar.sha256
      shell: bash
    - name: "Create new release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          dpppt-config-backend/target/dpppt-config-backend.jar
          dpppt-config-backend/generated/swagger/swagger.yaml
          dpppt-config-backend/target/dpppt-config-backend.jar.sha256
